apiVersion: apps/v1
kind: Deployment
metadata:
  name: movement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofka-movement
  template:
    metadata:
      labels:
        app: sofka-movement
    spec:
      containers:
        - name: sofka-movement
          image: alexer1515/movementsapp #Defino la imagen
          ports:
            - containerPort: 8085
          env:
            - name: appPort
              valueFrom:
                configMapKeyRef:
                  name: movement-config
                  key: appPort
            - name: mongoUri
              valueFrom:
                configMapKeyRef:
                  name: movement-config
                  key: mongoUri
            - name: mongoDatabase
              valueFrom:
                configMapKeyRef:
                  name: movement-config
                  key: mongoDatabase
            - name: rabbitUri
              valueFrom:
                configMapKeyRef:
                  name: movement-config
                  key: rabbitUri


---
apiVersion: v1
kind: Service
metadata:
  name: movements-service
spec:
  type: NodePort
  selector:
    app: sofka-movement
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30004